# Generated by Django 5.1.2 on 2024-11-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoutbox',
            name='event_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='eventoutbox',
            table=None,
        ),
    ]
